### ISSUE TITLE
How do you remove it from an app

### ISSUE THREAD

**Issue by westonganger** [jakeonrails/fix-db-schema-conflicts#2]
I commented it out because I am no longer working with someone on my project. But its still attempting to run and giving me errors about rubocop.

How do you remove it?

**Comment by jakeonrails** [comment]
I'm very concerned and not sure what exactly is happening here. Can you include a copy of your Gemfile? If it is not included in your Gemfile/bundle then it shouldn't ever have any impact on your project.

Also can you please share the errors you are seeing with Rubocop? Perhaps there is a fix that can solve that, which will allow you to continue using the gem!

**Comment by westonganger** [comment]
I checked my Gemfile and Gemfile.lock and there is no reference to it in either
I also searched my entire project for fix-db or rubocop and didnt find anything

Heres the error:
```
Dumping database schema with fix-db-schema-conflicts gem
/home/weston/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': rubocop is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /home/weston/.rbenv/versions/1.9.3-p551/bin/rubocop:22:in `<main>
```

**Comment by jakeonrails** [comment]
That's really strange. That error is definitely due to the gem not being included - rubocop is a dependency of the gem. If you re-enable it the error will go away, but I really can't come up with any reason the gem is still "active" despite being removed from your Gemfile.
The gem doesn't write any files to your local project directory or anything, and would have to be `require`d in order for the monkey patch that sorts the columns to get included (which is where the output you see - "Dumping database schema with fix-db-schema-conflicts gem" is coming from)

**Comment by jakeonrails** [comment]
Weston, could you try `gem uninstall`ing it? I wonder if it has something to do with Rbenv and the fact that there's a lib/tasks directory (maybe some sort of weird recursive rake thing to auto-include that somehow?)

**Comment by jakeonrails** [comment]
@westonganger Did you ever figure this one out?

**Comment by westonganger** [comment]
I cannot remember but I think gem uninstalled worked. I could have possibly fixed it by updating my projects gems.  Sorry I cannot include better details. Feel free to close this issue

**Comment by jakeonrails** [comment]
Ok cool. Thank you for following up!
